/* ===========================================================================
   tools/build.mjs - run every query in the book on real PostgreSQL and save
   what it printed.

       npm install          (once: fetches PGlite, PostgreSQL 18 in WebAssembly)
       npm run build        (writes book/outputs.js)

   What it checks, and fails the build on:
     - a lesson that errors without being marked `errors: true` (or the reverse)
     - a quiz question with a `check` query whose answer is not the marked option
     - a bug-hunt question whose marked fix still errors, or whose broken query
       neither errors nor is marked `silent: true`
     - a toolbox card whose example errors
   Outputs are keyed "<chapter id>/<page id>" and read by the page, so the
   saved output shown in the book is always what PostgreSQL really printed.
   =========================================================================== */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { PGlite } from "@electric-sql/pglite";
import { RAW_PARSERS, runScript, transcript, resetDB } from "../assets/sqlrun.js";
import { CHAPTERS, sandboxSQL, pageKey } from "../book/index.js";

const db = new PGlite({ parsers: RAW_PARSERS });
const out = {};
const problems = [];
const say = (m) => process.stdout.write(m + "\n");
const hasError = (blocks) => blocks.some((b) => b.kind === "error");
const norm = (s) => String(s ?? "").trim().toLowerCase().replace(/\s+/g, " ");

/* run inside a transaction that is always rolled back, so one quiz item
   can never change what the next one sees */
async function isolated(sql) {
  await db.exec("BEGIN");
  try { return await runScript(db, sql); }
  finally { await db.exec("ROLLBACK"); }
}

for (const ch of CHAPTERS) {
  let n = 0;
  await resetDB(db);
  /* 1. the story, in order: table pages and lessons build on each other */
  for (const p of ch.pages) {
    const key = pageKey(ch, p);
    if (p.kind === "table") {
      const set = await runScript(db, p.sql);
      if (hasError(set)) problems.push(`${key}: table setup errors\n${transcript(set)}`);
      out[key] = transcript(p.show ? await runScript(db, p.show) : set);
      n++;
    } else if (p.kind === "lesson") {
      const blocks = await runScript(db, p.sql);
      out[key] = transcript(blocks);
      if (hasError(blocks) && !p.errors) problems.push(`${key}: unexpected error\n${out[key]}`);
      if (!hasError(blocks) && p.errors) problems.push(`${key}: marked errors:true but ran clean`);
      n++;
    }
  }
  /* 2. toolbox, quiz and bug hunt all run against the chapter's sandbox */
  await resetDB(db);
  const sb = await runScript(db, sandboxSQL(ch));
  if (hasError(sb)) problems.push(`${ch.id}: sandbox setup errors\n${transcript(sb)}`);
  for (const p of ch.pages) {
    const key = pageKey(ch, p);
    if (p.kind === "tools") {
      for (const [i, c] of p.cards.entries()) {
        const b = await isolated(c.sql);
        out[`${key}/${i}`] = transcript(b);
        if (hasError(b) && !c.errors) problems.push(`${key}/${i} (${c.name}): card example errors\n${transcript(b)}`);
        n++;
      }
    } else if (p.kind === "quiz") {
      for (const [i, q] of p.qs.entries()) {
        if (!q.check) continue;
        const b = await isolated(q.check);
        const last = b[b.length - 1];
        const got = last && last.kind === "rows" ? last.rows[0]?.[0] : last?.kind === "error" ? "ERROR" : last?.text;
        const want = q.opts[q.a];
        if (norm(got) !== norm(String(want).replace(/^`|`$/g, "")))
          problems.push(`${key}/${i}: check returned "${got}" but the marked answer is "${want}"`);
        out[`${key}/${i}`] = transcript(b);
        n++;
      }
    } else if (p.kind === "debug") {
      for (const [i, q] of p.qs.entries()) {
        const bad = await isolated(q.bad);
        out[`${key}/${i}/bad`] = transcript(bad);
        if (!hasError(bad) && !q.silent) problems.push(`${key}/${i}: broken query ran clean (mark silent:true if intended)\n${q.bad}`);
        if (hasError(bad) && q.silent) problems.push(`${key}/${i}: marked silent but errors\n${transcript(bad)}`);
        const fix = await isolated(q.opts[q.a]);
        out[`${key}/${i}/fix`] = transcript(fix);
        if (hasError(fix)) problems.push(`${key}/${i}: the marked fix errors\n${transcript(fix)}`);
        n++;
      }
    }
  }
  say(`${ch.id.padEnd(5)} ${String(n).padStart(3)} runs  ${ch.title}`);
}

const file = fileURLToPath(new URL("../book/outputs.js", import.meta.url));
writeFileSync(file,
  "/* GENERATED by tools/build.mjs - do not edit. Every value is what PostgreSQL " +
  "18 printed for that query. */\nexport default " + JSON.stringify(out, null, 1) + ";\n");
say(`\nwrote ${Object.keys(out).length} outputs to book/outputs.js`);

/* GitHub Pages lets browsers cache every file for 10 minutes, so a reader
   could get new HTML with an old app.js. A fresh ?v= on each link makes the
   next reload fetch the new files. */
const V = new Date().toISOString().replace(/\D/g, "").slice(0, 12);
for (const [rel, re] of [["../index.html", /(assets\/(?:book\.css|app\.js))(\?v=\d+)?/g],
                         ["../assets/app.js", /(from "\.{1,2}\/(?:book\/index|book\/outputs|book\/narrate|art|pg)\.js)(\?v=\d+)?"/g]]) {
  const f = fileURLToPath(new URL(rel, import.meta.url));
  let src = readFileSync(f, "utf8").replace(re, (m, p) => `${p}?v=${V}${m.endsWith('"') ? '"' : ""}`);
  if (rel.endsWith("app.js")) src = src.replace(/const AUDIO_V = "\d+";/, `const AUDIO_V = "${V}";`);
  writeFileSync(f, src);
}
say(`stamped version ${V} on the page's links`);

if (problems.length) {
  say(`\n${problems.length} problem(s):\n`);
  for (const p of problems) say("- " + p + "\n");
  process.exit(1);
}
say("all checks passed");
